#!/bin/bash

echo "🧪 Bot Command Test"
echo "==================="
echo ""
echo "This will help you test if the bot is working."
echo ""

# Check if bot is running
if ps aux | grep -v grep | grep "node index.js" > /dev/null; then
    echo "✅ Bot is running"
    echo ""
    echo "📋 To test the bot:"
    echo ""
    echo "1. ⚠️  CLOSE WhatsApp Web (web.whatsapp.com) if it's open"
    echo "   - WhatsApp Web and the bot CANNOT run at the same time"
    echo "   - This causes conflicts and freezing"
    echo ""
    echo "2. 📱 Use a DIFFERENT phone to test"
    echo "   - The bot ignores messages from itself"
    echo "   - Have a friend send: .ping"
    echo "   - Or use a second phone"
    echo ""
    echo "3. 👀 Watch the bot terminal for logs:"
    echo "   - You should see [CMD] messages"
    echo "   - Example: [CMD] Command: ping"
    echo ""
    echo "4. ✅ Test commands:"
    echo "   .ping"
    echo "   .help"
    echo "   .alive"
    echo ""
    echo "📝 Common issues:"
    echo "   - WhatsApp Web open = Bot won't work"
    echo "   - Testing from same device = Bot ignores you"
    echo "   - Wrong prefix = Use . (dot) not /"
    echo ""
else
    echo "❌ Bot is NOT running"
    echo ""
    echo "Start the bot with:"
    echo "  npm start"
    echo ""
    echo "Then follow the test steps above."
fi
